name: Upload
description: Upload Extension.

runs:
  using: composite
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Godot_Whisper
        path: |
          ${{ github.workspace }}/bin/**
        retention-days: 14
