name: Build iOS
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}
  cancel-in-progress: true

env:
  OpenCL_ROOT: "${{ github.workspace }}/OpenCL-SDK"
  OpenCL_INCLUDE_DIR: "${{ github.workspace }}/OpenCL-SDK/build/install/include"
  OpenCL_LIBRARY: "${{ github.workspace }}/OpenCL-SDK/install/lib/OpenCL.lib"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - precision: single
            arch: arm64
            ios_precision_extension:
          - precision: double
            arch: arm64
            ios_precision_extension: .double
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build
        uses: godot/godot-cpp-template/.github/actions/build
        with:
          platform: ios
          arch: ${{ matrix.arch }}
          godot-cpp-location: godot-cpp
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot_Whisper
          path: |
            ${{ github.workspace }}/bin/**/libgodot_whisper.ios.template_release${{ matrix.ios_precision_extension }}.arm64.framework/**
          if-no-files-found: error
